apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    name: my-nginx-pod
    env: dev
spec:
  containers:
    - name: my-nginx-container
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
