apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: my-new-pods
      labels:
        app: myapp
    spec:
      containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort: 80
